/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Logger.samples;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
    private static final Logger LOGGER = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {

        // This is will be saved to the log file
        LOGGER.error("Error sample statement");
        SampleFunctionName();
    }

    private static void SampleFunctionName() {
        LOGGER.error("Function name will be printed together");
    }

}
